### ISSUE TITLE
Problem with 'Get started on GOV.UK'

### ISSUE THREAD

**Issue by maxgds** [alphagov/govuk-developer-docs#424]
Problem with 'Get started on GOV.UK' (https://docs.publishing.service.gov.uk/manual/get-started.html)

Section 8: Run your apps
This seems to be out of date. I can't run "bowl x" but have to run "bundle exec bowl x" to get any output. What then happens is the app runs and quits with a message that seems to suggest bundle exec wasn't previously run, even when it was:
/usr/lib/rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/source/git.rb:188:in `rescue in load_spec_files': git://github.com/alphagov/airbrake.git (at silence-dep-warnings-for-rails-5) is not yet checked out. Run `bundle install` first. (Bundler::GitError)

I've been pointed at an alternate way of running the apps which is to go into their directory and run the startup file from in there - does the documentation need to switch to instructing users to do this instead?

**Comment by h-lame** [comment]
Using `bowl <some-app>` from the `/var/govuk/govuk-puppet/development-vm` directory (no `bundle exec` required) is definitely the right way to run the apps.  You can run them using `startup.sh` from the `/var/govuk/<some-app>` folder too, but that won't run all the dependencies which is why we suggest using `bowl`.

I seem to recall talking to someone who hit this problem and they had to manually install `bowler` so it was available without using `bundle exec`.  Maybe by doing `gem install bowler` in the `/var/govuk/govuk-puppet` folder and then doing `rbenv rehash` (or opening a new shell), but these steps shouldn't be required - the VM _should_ work out of the box and these docs _should_ be correct.  Perhaps part of the provisioning of your VM failed; so maybe try rebuilding or reprovisioning it to make sure it's properly set up?

**Comment by maxgds** [comment]
I'm new here and a colleague pointed me at the solution of running the statup.sh - she started in July and got the instruction from a colleague who started a couple of months earlier - so I don't think this is isolated to my provisioning. After reading this I tried to install bowler directly and got permission errors:

Fetching: bowler-2.1.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /usr/lib/rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1 directory.

**Comment by h-lame** [comment]
We continued on slack, and doing `sudo gem install bowler` was enough to install bowler properly and be able to run apps using `bowl`.
